// DO NOT MODIFY THIS FILE, IT WILL BE OVERRIDE!!!
#ifndef _KENDRYTE_IDE_FLASH_MANGER_OUT_H
#define _KENDRYTE_IDE_FLASH_MANGER_OUT_H

#define KMODEL_START 0x601000
#define KMODEL_END 0x9BC000
#define KMODEL_SIZE 3908264

#endif // _KENDRYTE_IDE_FLASH_MANGER_OUT_H

